### ISSUE TITLE
有些人的連署好像迷路了

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [RainbowEngineer/taiwan_love_wins#444]
![default](https://cloud.githubusercontent.com/assets/13408130/21114061/cd030464-c0e6-11e6-8d66-70d49f6cc8e7.png)

有沒有辦法把這些沒回來的連署拉回來呢？還是一個一個通知他們發 PR？

**Comment by bater** [comment]
生命會找到出路，說不定他們還在猶豫呢ＸＤ
