### ISSUE TITLE
網站失效

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [RainbowEngineer/taiwan_love_wins#461]
如下圖：

![](https://user-images.githubusercontent.com/13408130/35160334-c98a5f2a-fd77-11e7-97ab-68376f43f3e1.png)

原本以為是域名失效了但是 whois 一下好像到年底的樣子

**Comment by etwu** [comment]
嗯，真的到期了我沒發現耶，這幾天我來續費好了，還在贖回期內（翻錢包）

**Comment by Lin-Buo-Ren** [comment]
感謝

需要財務上的支援請不吝提出

**Comment by Lin-Buo-Ren** [comment]
感謝

需要財務上的支援請不吝提出

**Comment by etwu** [comment]
費用會由我們性別不明關懷協會支出，非常歡迎贊助 ;)
http://www.istscare.org/donate/

**Comment by Lin-Buo-Ren** [comment]
感謝提供手滑方式 :-)

**Comment by etwu** [comment]
進度報告：
一週前付費了，不過網址還在贖回的路上~~~

**Comment by etwu** [comment]
感謝 @Lin-Buo-Ren ;)

**Comment by Lin-Buo-Ren** [comment]
不用客氣 (worship)

**Comment by etwu** [comment]
已經ticket給gandi了，這算大包了，因為gandi的系統上面顯示都正常

**Comment by etwu** [comment]
已經全部恢復正常，gandi工程師也幫忙處理完成了
